AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to complete AWS credit activities - EC2, Lambda, RDS, and Budgets (Bedrock requires manual console access)"

Parameters:
    EmailAddress:
        Type: String
        Description: Email address for budget and billing alerts
        AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
        ConstraintDescription: Must be a valid email address

    BudgetAmount:
        Type: Number
        Default: 1
        Description: Monthly budget amount in USD (minimum $1)
        MinValue: 1

    BillingAlarmThreshold:
        Type: Number
        Default: 0.10
        Description: Billing alarm threshold in USD (can be less than $1)

    LatestAmiId:
        Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
        Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
        Description: Latest Amazon Linux 2023 AMI ID

Resources:
    # ============================================
    # ACTIVITY 1: Set up a cost budget using AWS Budgets ($20 credit)
    # ============================================

    BudgetSNSTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: BudgetAlertTopic
            DisplayName: AWS Budget Alerts
            Subscription:
                - Endpoint: !Ref EmailAddress
                  Protocol: email

    MonthlyBudget:
        Type: AWS::Budgets::Budget
        Properties:
            Budget:
                BudgetName: MonthlySpendingBudget
                BudgetLimit:
                    Amount: !Ref BudgetAmount
                    Unit: USD
                TimeUnit: MONTHLY
                BudgetType: COST
            NotificationsWithSubscribers:
                - Notification:
                      NotificationType: ACTUAL
                      ComparisonOperator: GREATER_THAN
                      Threshold: 80
                  Subscribers:
                      - SubscriptionType: SNS
                        Address: !Ref BudgetSNSTopic
                - Notification:
                      NotificationType: FORECASTED
                      ComparisonOperator: GREATER_THAN
                      Threshold: 100
                  Subscribers:
                      - SubscriptionType: SNS
                        Address: !Ref BudgetSNSTopic

    # Billing alarm for custom threshold
    BillingAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub BillingAlert-${BillingAlarmThreshold}USD
            AlarmDescription: !Sub Alert when estimated charges exceed $${BillingAlarmThreshold}
            MetricName: EstimatedCharges
            Namespace: AWS/Billing
            Statistic: Maximum
            Period: 21600
            EvaluationPeriods: 1
            Threshold: !Ref BillingAlarmThreshold
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Currency
                  Value: USD
            AlarmActions:
                - !Ref BudgetSNSTopic
            TreatMissingData: notBreaching

    # ============================================
    # ACTIVITY 2: Launch an instance using EC2 ($20 credit)
    # ============================================

    EC2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for credit activity EC2 instance
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
                  Description: SSH access (restrict this in production!)
            Tags:
                - Key: Name
                  Value: CreditActivity-SG
                - Key: Purpose
                  Value: AWSCreditsActivity

    EC2Instance:
        Type: AWS::EC2::Instance
        DependsOn:
            - HelloWorldLambda
            - RDSInstance
            - MonthlyBudget
        Properties:
            InstanceType: t3.micro
            ImageId: !Ref LatestAmiId
            SecurityGroupIds:
                - !Ref EC2SecurityGroup
            Tags:
                - Key: Name
                  Value: CreditActivity-EC2
                - Key: Purpose
                  Value: AWSCreditsActivity
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    yum update -y
                    echo "EC2 instance launched for AWS credits activity" > /tmp/activity.log

    # ============================================
    # ACTIVITY 3: Create a web app using AWS Lambda ($20 credit)
    # ============================================

    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: CreditActivityLambdaRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Tags:
                - Key: Purpose
                  Value: AWSCreditsActivity

    HelloWorldLambda:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: CreditActivityWebApp
            Runtime: python3.12
            Handler: index.lambda_handler
            Role: !GetAtt LambdaExecutionRole.Arn
            Code:
                ZipFile: |
                    import json

                    def lambda_handler(event, context):
                        return {
                            'statusCode': 200,
                            'headers': {
                                'Content-Type': 'application/json',
                                'Access-Control-Allow-Origin': '*'
                            },
                            'body': json.dumps({
                                'message': 'Hello from AWS Lambda!',
                                'purpose': 'AWS Credits Activity',
                                'activity': 'Create a web app using AWS Lambda'
                            })
                        }
            Description: Simple web app for AWS credits activity
            Tags:
                - Key: Purpose
                  Value: AWSCreditsActivity

    LambdaFunctionUrl:
        Type: AWS::Lambda::Url
        Properties:
            TargetFunctionArn: !GetAtt HelloWorldLambda.Arn
            AuthType: NONE
            Cors:
                AllowOrigins:
                    - "*"
                AllowMethods:
                    - GET
                    - POST
                MaxAge: 300

    LambdaUrlPermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !Ref HelloWorldLambda
            Action: lambda:InvokeFunctionUrl
            Principal: "*"
            FunctionUrlAuthType: NONE

    # ============================================
    # ACTIVITY 4: Create an Aurora or RDS database ($20 credit)
    # ============================================

    RDSInstance:
        Type: AWS::RDS::DBInstance
        DeletionPolicy: Delete
        Properties:
            DBInstanceIdentifier: credit-activity-db
            DBInstanceClass: db.t3.micro
            Engine: mysql
            EngineVersion: "8.0.40"
            MasterUsername: admin
            MasterUserPassword: !Sub "{{resolve:secretsmanager:${DBSecret}:SecretString:password}}"
            AllocatedStorage: 20
            StorageType: gp3
            BackupRetentionPeriod: 1
            PreferredBackupWindow: 03:00-04:00
            PreferredMaintenanceWindow: mon:04:00-mon:05:00
            PubliclyAccessible: true
            Tags:
                - Key: Purpose
                  Value: AWSCreditsActivity

    DBSecret:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: CreditActivityDBPassword
            Description: RDS database password for credit activity
            GenerateSecretString:
                SecretStringTemplate: '{"username": "admin"}'
                GenerateStringKey: password
                PasswordLength: 16
                ExcludeCharacters: '"@/\'
            Tags:
                - Key: Purpose
                  Value: AWSCreditsActivity

Outputs:
    EC2InstanceId:
        Description: EC2 Instance ID
        Value: !Ref EC2Instance
        Export:
            Name: !Sub ${AWS::StackName}-EC2InstanceId

    EC2PublicIP:
        Description: EC2 Instance Public IP
        Value: !GetAtt EC2Instance.PublicIp
        Export:
            Name: !Sub ${AWS::StackName}-EC2PublicIP

    LambdaFunctionName:
        Description: Lambda Function Name
        Value: !Ref HelloWorldLambda
        Export:
            Name: !Sub ${AWS::StackName}-LambdaFunction

    LambdaFunctionURL:
        Description: Lambda Function URL (test this to complete the activity)
        Value: !GetAtt LambdaFunctionUrl.FunctionUrl
        Export:
            Name: !Sub ${AWS::StackName}-LambdaURL

    RDSEndpoint:
        Description: RDS Database Endpoint
        Value: !GetAtt RDSInstance.Endpoint.Address
        Export:
            Name: !Sub ${AWS::StackName}-RDSEndpoint

    RDSPort:
        Description: RDS Database Port
        Value: !GetAtt RDSInstance.Endpoint.Port
        Export:
            Name: !Sub ${AWS::StackName}-RDSPort

    DBSecretArn:
        Description: ARN of the Secrets Manager secret containing DB password
        Value: !Ref DBSecret
        Export:
            Name: !Sub ${AWS::StackName}-DBSecretArn

    BudgetName:
        Description: AWS Budget Name
        Value: MonthlySpendingBudget

    SNSTopicArn:
        Description: SNS Topic for Budget Alerts
        Value: !Ref BudgetSNSTopic
        Export:
            Name: !Sub ${AWS::StackName}-SNSTopic

    BedrockNote:
        Description: Bedrock Activity Instructions
        Value: "For Bedrock activity, manually visit AWS Console > Bedrock > Playgrounds and test a foundation model"
