AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple Budget and Billing Alarm template for cost protection"

Parameters:
    EmailAddress:
        Type: String
        Description: Email address for budget and billing alerts
        AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
        ConstraintDescription: Must be a valid email address

    BudgetAmount:
        Type: Number
        Default: 10
        Description: Monthly budget amount in USD
        MinValue: 1

    BillingAlarmThreshold:
        Type: Number
        Default: 5
        Description: Billing alarm threshold in USD

Resources:
    BudgetSNSTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: AWS Budget Alerts
            Subscription:
                - Endpoint: !Ref EmailAddress
                  Protocol: email

    MonthlyBudget:
        Type: AWS::Budgets::Budget
        Properties:
            Budget:
                BudgetName: MonthlySpendingBudget
                BudgetLimit:
                    Amount: !Ref BudgetAmount
                    Unit: USD
                TimeUnit: MONTHLY
                BudgetType: COST
            NotificationsWithSubscribers:
                - Notification:
                      NotificationType: ACTUAL
                      ComparisonOperator: GREATER_THAN
                      Threshold: 80
                  Subscribers:
                      - SubscriptionType: SNS
                        Address: !Ref BudgetSNSTopic
                - Notification:
                      NotificationType: FORECASTED
                      ComparisonOperator: GREATER_THAN
                      Threshold: 100
                  Subscribers:
                      - SubscriptionType: SNS
                        Address: !Ref BudgetSNSTopic

    BillingAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub BillingAlert-${BillingAlarmThreshold}USD
            AlarmDescription: !Sub Alert when estimated charges exceed $${BillingAlarmThreshold}
            MetricName: EstimatedCharges
            Namespace: AWS/Billing
            Statistic: Maximum
            Period: 21600
            EvaluationPeriods: 1
            Threshold: !Ref BillingAlarmThreshold
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Currency
                  Value: USD
            AlarmActions:
                - !Ref BudgetSNSTopic
            TreatMissingData: notBreaching

Outputs:
    SNSTopicArn:
        Description: SNS Topic for Budget Alerts
        Value: !Ref BudgetSNSTopic

    BudgetName:
        Description: AWS Budget Name
        Value: MonthlySpendingBudget

    BillingAlarmName:
        Description: CloudWatch Billing Alarm Name
        Value: !Ref BillingAlarm
